## Домашняя работа по МО.
Работу выполнил студент ПМ22-5 Саркисян Мгер.

1. С помощью массивов numpy создайте таблицу умножения.

In [ ]:
import numpy as np

n = 9

table = np.empty((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        table[i, j] = (i + 1) * (j + 1)

print(table)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


2. Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число), и разность (вещественное число) и создает матрицу numpy по диагонали, которой располагаются первые N членов арифметической прогрессии.

In [ ]:
def create_ap_matrix(N, first_element, difference):
    progression = np.arange(first_element, first_element + N * difference, difference)

    matrix = np.zeros((N, N), dtype=float)

    np.fill_diagonal(matrix, progression)

    return matrix

N = 5  # Количество членов прогрессии
first_element = 2.0  # Первый элемент прогрессии
difference = 3.0  # Разность между членами прогрессии

result_matrix = create_ap_matrix(N, first_element, difference)
print(result_matrix)

[[ 2.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.]
 [ 0.  0.  8.  0.  0.]
 [ 0.  0.  0. 11.  0.]
 [ 0.  0.  0.  0. 14.]]


3. Сгенерируйте средствами numpy матрицу А 5 на 5, содержащую последовательные числа от 1 до 25. Используя срезы извлеките в плоский массив все нечетные элементы этой матрицы.

In [ ]:
A = np.arange(1, 26).reshape(5, 5)
#print(A)

odd_elements = A[A % 2 != 0]

print(odd_elements)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


4. Создайте двумерный массив, содержащий единицы на границе и нули внутри.

In [ ]:
rows = 6
cols = 8

matrix = np.zeros((rows, cols), dtype=int)

matrix[0, :] = 1  # Верхняя граница
matrix[-1, :] = 1  # Нижняя граница
matrix[:, 0] = 1  # Левая граница
matrix[:, -1] = 1  # Правая граница

print(matrix)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


5. Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержащую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы.

In [ ]:
matrix_chess = np.array([[5, 0, 5, 0, 5],
                         [0, 5, 0, 5, 0],
                         [5, 0, 5, 0, 5],
                         [0, 5, 0, 5, 0],
                         [5, 0, 5, 0, 5]])

# создание треугольной матрицы с 5 на основной диагонали и нулями выше и ниже
matrix_triangle = np.tri(5, 5) * 5

# находим детерминанты
det_chess = np.linalg.det(matrix_chess)
det_triangle = np.linalg.det(matrix_triangle)

# находим обратные матрицы
try:
    inv_chess = np.linalg.inv(matrix_chess)
    inv_triangle = np.linalg.inv(matrix_triangle)
except np.linalg.LinAlgError:
    inv_chess = "Обратной матрицы не существует"
    inv_triangle = "Обратной матрицы не существует"

# вывод
print("Матрица с 'шахматным' распределением числа 5:")
print(matrix_chess)
print("Детерминант матрицы с 'шахматным' распределением числа 5:", det_chess)
print("Обратная матрица с 'шахматным' распределением числа 5:")
print(inv_chess)

print("\nТреугольная матрица с 5 на основной диагонали:")
print(matrix_triangle)
print("Детерминант треугольной матрицы:", det_triangle)
print("Обратная треугольная матрица:")
print(inv_triangle)

Матрица с 'шахматным' распределением числа 5:
[[5 0 5 0 5]
 [0 5 0 5 0]
 [5 0 5 0 5]
 [0 5 0 5 0]
 [5 0 5 0 5]]
Детерминант матрицы с 'шахматным' распределением числа 5: 0.0
Обратная матрица с 'шахматным' распределением числа 5:
Обратной матрицы не существует

Треугольная матрица с 5 на основной диагонали:
[[5. 0. 0. 0. 0.]
 [5. 5. 0. 0. 0.]
 [5. 5. 5. 0. 0.]
 [5. 5. 5. 5. 0.]
 [5. 5. 5. 5. 5.]]
Детерминант треугольной матрицы: 3124.999999999999
Обратная треугольная матрица:
Обратной матрицы не существует


6. С помощью pandas загрузите датасет для предсказания цены квартиры, прилагающийся к этой работе.

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.head())

      Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   
3   2352           1    1.0   40.409907         NaN            1.0     10   
4  13866          94    2.0   64.285067   38.562517            9.0     16   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   
3        22.0       1977   0.007122         B         B         1       264   
4        16.0       1972   0.282798         B         B        33      8667   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2       

7. Выведите на экран несколько первых и несколько последний строк файла.

In [ ]:
print(df.head())

      Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   
3   2352           1    1.0   40.409907         NaN            1.0     10   
4  13866          94    2.0   64.285067   38.562517            9.0     16   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   
3        22.0       1977   0.007122         B         B         1       264   
4        16.0       1972   0.282798         B         B        33      8667   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2       

In [ ]:
print(df.tail())

         Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
9995   1260          61    2.0  49.090728   33.272626            6.0      3   
9996  16265          27    2.0  64.307684   37.038420            9.0     13   
9997   2795         178    1.0  29.648057   16.555363            5.0      3   
9998  14561          21    1.0  32.330292   22.326870            5.0      3   
9999   7202          94    1.0  35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
9995        12.0       1981   0.300323         B         B        52   
9996         0.0       1977   0.072158         B         B         2   
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
9995     10311      

8. Выведите с помощью методов pandas основные количественные параметры датасета: количество строк и столбцов, тип данных каждого поля, количество значений в каждом столбце, шкала измерения каждого численного поля.

In [ ]:
print("Информация о датасете:")
print(df.info())

Информация о датасете:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             10000 non-null  int64  
 1   DistrictId     10000 non-null  int64  
 2   Rooms          10000 non-null  float64
 3   Square         10000 non-null  float64
 4   LifeSquare     7887 non-null   float64
 5   KitchenSquare  10000 non-null  float64
 6   Floor          10000 non-null  int64  
 7   HouseFloor     10000 non-null  float64
 8   HouseYear      10000 non-null  int64  
 9   Ecology_1      10000 non-null  float64
 10  Ecology_2      10000 non-null  object 
 11  Ecology_3      10000 non-null  object 
 12  Social_1       10000 non-null  int64  
 13  Social_2       10000 non-null  int64  
 14  Social_3       10000 non-null  int64  
 15  Healthcare_1   5202 non-null   float64
 16  Helthcare_2    10000 non-null  int64  
 17  Shops_1        10000 non-nul

In [ ]:
print("Основные статистические характеристики:")
print(df.describe())

Основные статистические характеристики:
                Id    DistrictId         Rooms        Square   LifeSquare  \
count  10000.00000  10000.000000  10000.000000  10000.000000  7887.000000   
mean    8383.40770     50.400800      1.890500     56.315775    37.199645   
std     4859.01902     43.587592      0.839512     21.058732    86.241209   
min        0.00000      0.000000      0.000000      1.136859     0.370619   
25%     4169.50000     20.000000      1.000000     41.774881    22.769832   
50%     8394.50000     36.000000      2.000000     52.513310    32.781260   
75%    12592.50000     75.000000      2.000000     65.900625    45.128803   
max    16798.00000    209.000000     19.000000    641.065193  7480.592129   

       KitchenSquare         Floor    HouseFloor     HouseYear     Ecology_1  \
count   10000.000000  10000.000000  10000.000000  1.000000e+04  10000.000000   
mean        6.273300      8.526700     12.609400  3.990166e+03      0.118858   
std        28.560917      

In [ ]:
print("Количество уникальных значений в каждом столбце:")
print(df.nunique())

Количество уникальных значений в каждом столбце:
Id               10000
DistrictId         205
Rooms                9
Square           10000
LifeSquare        7887
KitchenSquare       58
Floor               33
HouseFloor          44
HouseYear           97
Ecology_1          129
Ecology_2            2
Ecology_3            2
Social_1            51
Social_2           142
Social_3            30
Healthcare_1        79
Helthcare_2          7
Shops_1             16
Shops_2              2
Price            10000
dtype: int64


In [ ]:
print("Тип данных каждого поля:")
print(df.dtypes)

Тип данных каждого поля:
Id                 int64
DistrictId         int64
Rooms            float64
Square           float64
LifeSquare       float64
KitchenSquare    float64
Floor              int64
HouseFloor       float64
HouseYear          int64
Ecology_1        float64
Ecology_2         object
Ecology_3         object
Social_1           int64
Social_2           int64
Social_3           int64
Healthcare_1     float64
Helthcare_2        int64
Shops_1            int64
Shops_2           object
Price            float64
dtype: object


9. Удалите из таблицы столбцы, содержащие идентификаторы, переименуйте все оставшиеся названия колонок на русском языке.

In [ ]:
df.drop(columns = ['Id', 'DistrictId'], axis=1, inplace = True)
df.columns = ['Комнаты', 'Квадратные метры', 'Жилая площадь', 'Площадь кухни', 'Этаж', 'ДомЭтаж', 'Год строительства', 'Экология_1', 'Экология_2', 'Экология_3', 'Общество_1', 'Общество_2', 'Общество_3', 'Больница_1', 'Больница_2', 'Магазин_1', 'Магазин_2', 'Цена']

In [ ]:
df.head()

Комнаты  Квадратные метры  Жилая площадь  Площадь кухни  Этаж  ДомЭтаж  \
0      3.0        115.027311            NaN           10.0     4     10.0   
1      1.0         39.832524      23.169223            8.0     7      8.0   
2      3.0         78.342215      47.671972           10.0     2     17.0   
3      1.0         40.409907            NaN            1.0    10     22.0   
4      2.0         64.285067      38.562517            9.0    16     16.0   

   Год строительства  Экология_1 Экология_2 Экология_3  Общество_1  \
0               2014    0.075424          B          B          11   
1               1966    0.118537          B          B          30   
2               1988    0.025609          B          B          33   
3               1977    0.007122          B          B           1   
4               1972    0.282798          B          B          33   

   Общество_2  Общество_3  Больница_1  Больница_2  Магазин_1 Магазин_2  \
0        3097           0         NaN           0          0         B   
1        6207           1      1183.0           1          0         B   
2        5261           0       240.0           3          1         B   
3         264           0         NaN           0          1         B   
4        8667           2         NaN           0          6         B   

            Цена  
0  305018.871089  
1  177734.553407  
2  282078.720850  
3  168106.007630  
4  343995.102962

10. Выведите отдельно столбец, содержащий цену, по номеру и названию. Выведите первую, десятую и предпоследнюю строку таблицы по номеру и по индексу.

In [ ]:
print(df['Цена'])
print(df[df.columns[-1]])
print(df.loc[1])
print(df.loc[10])
print(df.loc[9999])
print(df.iloc[0])
print(df.iloc[9])
print(df.iloc[-1])

0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64
0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64
Комнаты                        1.0
Квадратные метры         39.832524
Жилая площадь            23.169223
Площадь кухни                  8.0
Этаж                             7
ДомЭтаж                        8.0
Год строительства             1966
Экология_1                0.118537
Экология_2                       B
Экология_3                       B
Общество_1                      30
Общество_2                    6207
Общество_3  

11. Выделите в отдельную таблицу последние десять строк. Уберите в ней столбец с ценой. Склейте ее с первоначальной таблицей при помощи append. Заполните отсутствующие значения цены средним по таблице.

In [ ]:
df_2 = df.tail(10)
df_2 = df_2.drop(columns = ['Цена'], axis=1)
df = pd.concat([df, df_2], ignore_index=True)
df['Цена'].iloc[10000:10010] = df['Цена'].mean()

<ipython-input-32-c7a9a29bcd2a>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Цена'].iloc[10000:10010] = df['Цена'].mean()


Комнаты  Квадратные метры  Жилая площадь  Площадь кухни  Этаж  ДомЭтаж  \
0          3.0        115.027311            NaN           10.0     4     10.0   
1          1.0         39.832524      23.169223            8.0     7      8.0   
2          3.0         78.342215      47.671972           10.0     2     17.0   
3          1.0         40.409907            NaN            1.0    10     22.0   
4          2.0         64.285067      38.562517            9.0    16     16.0   
...        ...               ...            ...            ...   ...      ...   
10015      2.0         49.090728      33.272626            6.0     3     12.0   
10016      2.0         64.307684      37.038420            9.0    13      0.0   
10017      1.0         29.648057      16.555363            5.0     3      5.0   
10018      1.0         32.330292      22.326870            5.0     3      9.0   
10019      1.0         35.815476      22.301367            6.0     9      9.0   

       Год строительства  Экология_1 Экология_2 Экология_3  Общество_1  \
0                   2014    0.075424          B          B          11   
1                   1966    0.118537          B          B          30   
2                   1988    0.025609          B          B          33   
3                   1977    0.007122          B          B           1   
4                   1972    0.282798          B          B          33   
...                  ...         ...        ...        ...         ...   
10015               1981    0.300323          B          B          52   
10016               1977    0.072158          B          B           2   
10017               1958    0.460556          B          B          20   
10018               1969    0.194489          B          B          47   
10019               1975    0.127376          B          B          43   

       Общество_2  Общество_3  Больница_1  Больница_2  Магазин_1 Магазин_2  \
0            3097           0         NaN           0          0         B   
1            6207           1      1183.0           1          0         B   
2            5261           0       240.0           3          1         B   
3             264           0         NaN           0          1         B   
4            8667           2         NaN           0          6         B   
...           ...         ...         ...         ...        ...       ...   
10015       10311           6         NaN           1          9         B   
10016         629           1         NaN           0          0         A   
10017        4386          14         NaN           1          5         B   
10018        8004           3       125.0           3          5         B   
10019        8429           3         NaN           3          9         B   

                Цена  
0      305018.871089  
1      177734.553407  
2      282078.720850  
3      168106.007630  
4      343995.102962  
...              ...  
10015            NaN  
10016            NaN  
10017            NaN  
10018            NaN  
10019            NaN  

[10020 rows x 18 columns]

12. Выделите пять последних колонок в отдельную таблицу. Удалите в ней строки, в которых цена ниже среднего. Присоедините эту таблицу к изначальной (выберите самый подходящий тип соединения).

In [ ]:
df_2 = df.tail(5)
df_2 = df_2[df_2['Цена'] < df_2['Цена'].mean()]
pd.concat([df, df_2], ignore_index=True)

Комнаты  Квадратные метры  Жилая площадь  Площадь кухни  Этаж  ДомЭтаж  \
0          3.0        115.027311            NaN           10.0     4     10.0   
1          1.0         39.832524      23.169223            8.0     7      8.0   
2          3.0         78.342215      47.671972           10.0     2     17.0   
3          1.0         40.409907            NaN            1.0    10     22.0   
4          2.0         64.285067      38.562517            9.0    16     16.0   
...        ...               ...            ...            ...   ...      ...   
10005      2.0         49.090728      33.272626            6.0     3     12.0   
10006      2.0         64.307684      37.038420            9.0    13      0.0   
10007      1.0         29.648057      16.555363            5.0     3      5.0   
10008      1.0         32.330292      22.326870            5.0     3      9.0   
10009      1.0         35.815476      22.301367            6.0     9      9.0   

       Год строительства  Экология_1 Экология_2 Экология_3  Общество_1  \
0                   2014    0.075424          B          B          11   
1                   1966    0.118537          B          B          30   
2                   1988    0.025609          B          B          33   
3                   1977    0.007122          B          B           1   
4                   1972    0.282798          B          B          33   
...                  ...         ...        ...        ...         ...   
10005               1981    0.300323          B          B          52   
10006               1977    0.072158          B          B           2   
10007               1958    0.460556          B          B          20   
10008               1969    0.194489          B          B          47   
10009               1975    0.127376          B          B          43   

       Общество_2  Общество_3  Больница_1  Больница_2  Магазин_1 Магазин_2  \
0            3097           0         NaN           0          0         B   
1            6207           1      1183.0           1          0         B   
2            5261           0       240.0           3          1         B   
3             264           0         NaN           0          1         B   
4            8667           2         NaN           0          6         B   
...           ...         ...         ...         ...        ...       ...   
10005       10311           6         NaN           1          9         B   
10006         629           1         NaN           0          0         A   
10007        4386          14         NaN           1          5         B   
10008        8004           3       125.0           3          5         B   
10009        8429           3         NaN           3          9         B   

                Цена  
0      305018.871089  
1      177734.553407  
2      282078.720850  
3      168106.007630  
4      343995.102962  
...              ...  
10005  214138.857399  
10006  214138.857399  
10007  214138.857399  
10008  214138.857399  
10009  214138.857399  

[10010 rows x 18 columns]

13. Выведите таблицу, содержащую среднюю цену и количество квартир на каждом этаже из первоначального набора данных.

In [ ]:
df['Этаж'] = df['Этаж'].astype('int64')
df_13 = df.groupby(['Этаж'])[['Комнаты', 'Цена']].mean()

df_13

Комнаты           Цена
Этаж                         
1     1.851695  181336.712641
2     1.901361  200054.515039
3     1.896000  197117.126020
4     1.936909  206770.686855
5     1.873288  208642.097899
6     1.887920  213621.462621
7     1.936759  219149.530324
8     1.877138  217291.383083
9     1.889256  218580.878248
10    1.858951  212030.108560
11    1.846827  213094.735844
12    1.792711  211678.543857
13    1.872180  215102.243736
14    1.895028  231031.896587
15    1.912892  234276.528574
16    1.827586  222327.410321
17    1.937500  219896.414764
18    1.875676  230055.477403
19    1.925620  229093.752512
20    1.808824  244087.213465
21    1.779661  243138.009099
22    2.314815  289708.585988
23    1.960000  277347.739049
24    1.886792  262331.096642
25    2.235294  270813.232998
26    2.333333  313255.149648
27    2.000000  238152.827407
28    1.333333  310932.492847
31    1.000000  117647.461002
32    1.000000  245640.188762
33    1.000000  389554.063540
37    1.000000  269113.584248
42    2.000000  411691.504766

14. Сохраните получившуюся таблицу в файлы формата csv и xlsx. Прочитайте их и убедитесь, что данные отображаются корректно.

In [ ]:
df_13.to_csv('out.csv',index = False)
df_13.to_excel('out.xlsx',index = False)

15. Создайте в Excel или другом табличном редакторе таблицу, содержащую несколько численных и текстовых полей. Прочитайте ее в программу при помощи pandas.

In [ ]:
pd.read_excel("test_file.xlsx")

2123    213213  34    
0  3123213   21323       2
1      123    5435       4
2       13      23  436754
3       12       4    3254
4     3123      53      25